# Generated by Django 4.0.5 on 2022-07-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_order_course_remove_order_like_order_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='order',
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
